// ReactJs/examen/src/componentes/BarraNavegacion/BarraNavegacion.js
import React, { Component } from 'react';
import {
    Collapse,
    Navbar,
    NavbarToggler,
    NavbarBrand,
    Nav,
    NavItem,
    NavLink
     } from 'reactstrap';
import './BarraNavegacion.css';


class Barranavegacion extends Component {

    constructor(props) {
        super(props);

        this.toggle = this.toggle.bind(this);
        this.state = {
            isOpen: false
        };
    }

    toggle() {
        this.setState({
            isOpen: !this.state.isOpen
        });
    }

    render() {
      return (
        <div >
            <Navbar color="light" light expand="xs" >
                <NavbarBrand href="/catalogo">La bodega</NavbarBrand>
                <NavbarToggler onClick={this.toggle} />
                <Collapse isOpen={this.state.isOpen} navbar>
                    <Nav className="ml-auto" navbar>
                    <NavItem>
                    <NavLink href="/catalogo"><img width="20px" height="20px" src={require("../../recursos/iconos/002-show-apps-button.svg")}/></NavLink>
                    </NavItem>
                    <NavItem>
                    <NavLink href="#"><img width="20px" height="20px" src={require("../../recursos/iconos/004-commerce.svg")}/><span class="badge badge-danger badge-pill"></span></NavLink>
                    </NavItem>
                    <NavItem>
                    <NavLink href="#"><img width="20px" height="20px" src={require("../../recursos/iconos/001-inbox.svg")}/></NavLink>
                    </NavItem>
                    <NavItem>
                    <NavLink onClick={this.CerrarSesion} ><img width="20px" height="20px" src={require("../../recursos/iconos/003-logout.svg")}/></NavLink>
                    </NavItem>
                    </Nav>
                </Collapse>
            </Navbar>
        </div>
      );
    }
  
  CerrarSesion(){
    window.localStorage.setItem("idUsuario","0");
    window.location.pathname="/login";
  }
}
  
  export default Barranavegacion;

// Angular/angular/src/app/barra-navegacion/barra-navegacion.component.ts
import { Component, OnInit } from '@angular/core';



@Component({
  selector: 'barra-navegacion',
  templateUrl: './barra-navegacion.component.html',
  styleUrls: ['./barra-navegacion.component.css']
})
export class barranavegacionComponent implements OnInit {

  
  constructor() {
    if(window.localStorage.getItem('id')==""){
      window.location.href="/";    
    }
   }

  cerrarSesion(){
    window.localStorage.setItem('id','');
    window.location.href="/";    
  }

  ngOnInit() {
   
  }
}
<header>
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
          <a class="navbar-brand" href="/catalogo">La bodega</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
  
          <div class="collapse navbar-collapse justify-content-md-end" id="navbarsExample10">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="/catalogo"><img width="20px" height="20px" src="../recursos/iconos/002-show-apps-button.svg"></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/carrocompras"><img width="20px" height="20px" src="../recursos/iconos/004-commerce.svg"><span class="badge badge-danger badge-pill">9</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="/catalogo"><img width="20px" height="20px" src="../recursos/iconos/001-inbox.svg"></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" (click)="cerrarSesion()"><img width="20px" height="20px" src="../recursos/iconos/003-logout.svg"></a>
              </li>
            </ul>
          </div>
        </nav>
  </header>
